# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import morse
import time



class Ui_Morse_GUI(object):
    def __init__(self):
        super.__init__()
        self.morse_converter = morse.morse()

    def setupUi(self, Morse_GUI):
        Morse_GUI.setObjectName("Morse_GUI")
        Morse_GUI.resize(526, 442)
        self.centralwidget = QtWidgets.QWidget(Morse_GUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.inputbox = QtWidgets.QLineEdit(self.centralwidget)
        self.inputbox.setGeometry(QtCore.QRect(240, 90, 211, 31))
        self.inputbox.setMaxLength(12)
        self.inputbox.setObjectName("inputbox")
        self.text_in_morse_label = QtWidgets.QLabel(self.centralwidget)
        self.text_in_morse_label.setGeometry(QtCore.QRect(60, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.text_in_morse_label.setFont(font)
        self.text_in_morse_label.setObjectName("text_in_morse_label")
        self.morse_code_label = QtWidgets.QLabel(self.centralwidget)
        self.morse_code_label.setGeometry(QtCore.QRect(220, 160, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cantarell Thin")
        font.setPointSize(14)
        self.morse_code_label.setFont(font)
        self.morse_code_label.setTextFormat(QtCore.Qt.RichText)
        self.morse_code_label.setScaledContents(True)
        self.morse_code_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.morse_code_label.setIndent(10)
        self.morse_code_label.setObjectName("morse_code_label")
        self.convert_Button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.convert_button_clicked() )
        self.convert_Button.setGeometry(QtCore.QRect(190, 300, 131, 51))
        self.convert_Button.setObjectName("convert_Button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 240, 171, 41))
        font = QtGui.QFont()

        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.current_letter = QtWidgets.QLabel(self.centralwidget)
        self.current_letter.setGeometry(QtCore.QRect(350, 240, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Cantarell Thin")
        self.current_letter.setFont(font)
        self.current_letter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_letter.setIndent(10)
        self.current_letter.setObjectName("current_letter")
        Morse_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Morse_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 27))
        self.menubar.setObjectName("menubar")
        Morse_GUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Morse_GUI)
        self.statusbar.setObjectName("statusbar")
        Morse_GUI.setStatusBar(self.statusbar)

        self.retranslateUi(Morse_GUI)
        QtCore.QMetaObject.connectSlotsByName(Morse_GUI)

    def retranslateUi(self, Morse_GUI):
        _translate = QtCore.QCoreApplication.translate
        Morse_GUI.setWindowTitle(_translate("Morse_GUI", "MainWindow"))
        self.label.setText(_translate("Morse_GUI", "Text to Convert: "))
        self.text_in_morse_label.setText(_translate("Morse_GUI", "Text In Morse: "))
        self.morse_code_label.setText(_translate("Morse_GUI", "Morse Code"))
        self.convert_Button.setText(_translate("Morse_GUI", "Convert"))
        self.label_2.setText(_translate("Morse_GUI", "Current Letter on LED: "))
        self.current_letter.setText(_translate("Morse_GUI", "A-Z"))

    def convert_button_clicked(self):
        self.convert_Button.setDisabled()
        self.inputbox.setDisabled()

        try:
            self.result = self.morse_converter.translate()
            self.morse_code_label.setText(self.result)
        except LookupError as e:
            self.error = str(e)
        finally:
            self.morse_code_label.setText(self.error)
            self.current_letter.setText(self.error)
            time.sleep(1)
            self.inputbox.setEnabled()
            self.convert_Button.setEnabled()

        for x in self.inputbox.text():
            if x in morse.morse_dict.keys():
                self.current_letter.setText(x)
                self.morse_converter.blink_letter(x)

            else:
                break
        self.inputbox.setEnabled()
        self.convert_Button.setEnabled()